[project]
name = "chat-app"
version = "0.1.0"
description = "Production-ready Web Chat Application"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi",
    "uvicorn",
    "langchain==1.2.10",
    "langgraph==1.0.9",
    "litellm",
    "python-dotenv",
    "pydantic",
    "pydantic-settings",
    "streamlit",
    "langchain-openai",
    "langchain-anthropic",
    "langchain-google-genai",
    "motor>=3.7.1",
    "dnspython>=2.8.0",
    "celery[redis]>=5.6.2",
    "redis>=6.4.0",
    "faiss-cpu>=1.13.2",
    "langchain-community>=0.4.1",
    "pypdf>=6.7.3",
    "sentence-transformers>=5.2.3",
    "python-multipart>=0.0.22",
    "langchain-huggingface>=1.2.0",
    "sse-starlette>=3.3.2",
    "pinecone>=8.1.0",
    "langchain-text-splitters>=1.1.1",
]
